channels:
  - pytorch
  - anaconda
  - conda-forge
  - nvidia
  - xformers/label/dev
dependencies:
  - python=3.10
  - pip
  - pip:
      - ipykernel~=6.20.2
      - azureml-core==1.49.0
      - azureml-dataset-runtime==1.49.0
      - azureml-defaults==1.49.0
      - azure-ml==0.0.1
      - azure-ml-component==0.9.17
      - azureml-mlflow==1.49.0
      - azureml-contrib-services==1.49.0
      - torch-tb-profiler~=0.4.0
      - py-spy==0.3.12
      - debugpy~=1.6.3
      - MarkupSafe==2.1.1
      - regex
      - pybind11
      - mlflow
      - nvitop
      - transformers
      - joblib
      - datasets
      - sentencepiece
      - diffusers
      - matplotlib
      - fastcore
      - fastdownload
      - huggingface_hub
      - jupyter
      - triton
      - wandb
      - salesforce-lavis
      - Pillow
      - azureml-inference-server-http
      - azureml-contrib-services
      - accelerate
      - opencv-python
      - python-dotenv
      - controlnet-aux
      - safetensors
      - loras
      - compel
      - deepspeed
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - xformers


